name: Docker CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out the code from the repository

      # Step 2: Set up Docker Buildx (needed for advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Sets up Buildx for advanced Docker builds

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Use the Docker username stored in secrets
          password: ${{ secrets.DOCKER_PASSWORD }}   # Use the Docker password stored in secrets

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t yourusername/test-automation:${{ github.sha }} .  # Replace 'yourusername' with your actual Docker username in lowercase

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push yourusername/test-automation:${{ github.sha }}  # Push image to Docker Hub

      # Step 6: Send email notification
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Using Gmail's SMTP server
          server_port: 587                # SMTP port for Gmail
          username: ${{ secrets.EMAIL_USERNAME }}  # Email username stored in secrets
          password: ${{ secrets.EMAIL_PASSWORD }}  # Email password stored in secrets
          subject: CI/CD Pipeline Notification
          body: |
            The build and run was completed successfully! You can view the details of the job at the link below:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: |
            f223654@cfd.nu.edu.pk, f223686@cfd.nu.edu.pk  # Add multiple recipients by separating emails with commas
          from: ${{ secrets.EMAIL_USERNAME }}  # Use the same email as the sender
