name: Docker CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out the code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Sets up Buildx for advanced Docker builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ramday  # Replace with your Docker Hub username
          password: darknight328  # Replace with your Docker Hub password or token

      - name: Build Docker image
        run: |
          docker build -t ramday/test-automation:${{ github.sha }} .  # Replace YOUR_DOCKER_USERNAME with your username and tag the image with commit SHA

      - name: Push Docker image to Docker Hub
        run: |
          docker push ramday/test-automation:${{ github.sha }}  # Push image to Docker Hub
